### ISSUE TITLE
Нет реакции на заявленные команды

### ISSUE THREAD

**Issue by esineokov** [Gluyk-1/stop_boring#1]
После вступления в чат бот выдает текст в котором есть: `Для игры используйте команду /film или “Бот, сыграем в угадай фильм`
На данные команды бот никак не реагирует и игру не начинает.

Данное поведение на всех играх.

**Comment by Gluyk-1** [comment]
Это команды не это бота. А бота https://icq.im/PartyBot
Он выполняет все игровые действия в чате и отвечает за игру. 
Бот https://icq.im/super_admin_bot
Отвечает за модерацию чата
По этому это не относится к командам бота

**Comment by esineokov** [comment]
То есть, этот без него работать не будет? Нужно хоть где-то минимально описание по зависимостям.

**Comment by esineokov** [comment]
super_admin_bot должен всегда добавляться во все чаты автоматически?

**Comment by Gluyk-1** [comment]
Нет. Это разные боты. Мой именно, что бы создать чат и закинуть туда людей. Пати для того, что люди играли.

**Comment by Gluyk-1** [comment]
super_admin_bot и пати бот должен всегда добавляться в чаты и ещё один пользователь, с которого админы будут сидеть и смотреть за чатам.
Админку нужно дать супер админу и пользователю

**Comment by Gluyk-1** [comment]
Все изменения были залиты + добавил некоторое описание

**Comment by esineokov** [comment]
Эти боты не наши?
https://icq.im/PartyBot
https://icq.im/super_admin_bot
Поднять их отдельно и потестировать нельзя будет?

**Comment by Gluyk-1** [comment]
https://icq.im/PartyBot - это бот @VictorTolstov Виктора Толстово
https://icq.im/super_admin_bot - это мой бот, но написан он на php7.3)
