### ISSUE TITLE
Выкинуло из чата до истечения 15 минут

### ISSUE THREAD

**Issue by esineokov** [Gluyk-1/stop_boring#12]
3) Выкинуло из чата до истечения 15 минут. При этом сообщение от бота осталось прежним с ссылкой на этот чат. При переходе чат открывается с "удалить и выйти". После удаления чата, повторного перехода по ссылке на него и нажатии на "вступить" выкидывает (удаляет) из чата

**Comment by Gluyk-1** [comment]
Исправил
