### ISSUE TITLE
Нет файла {bot_name}.service.example

### ISSUE THREAD

**Issue by esineokov** [Gluyk-1/stop_boring#6]
https://github.com/mail-ru-im/bot-python-async#%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D0%B8

**Comment by Gluyk-1** [comment]
![image](https://user-images.githubusercontent.com/69149831/93469430-13d32e00-f923-11ea-842f-5d77ec6cfa53.png)
А для чего он?

**Comment by Gluyk-1** [comment]
Что в нём должно быть?

**Comment by esineokov** [comment]
https://github.com/mail-ru-im/bot-python-async/blob/master/example/test_bot.service.example
Файл для добавления в systemd. Для автостарта.
